### ISSUE TITLE
Boss Animation

### ISSUE THREAD

**Issue by dhagandev** [anuragpapineni/3DCapstoneGame#120]

**Comment by JasonCheon** [comment]
I put a [?] next to the animations I'm not sure of.

Normal Phase Idle
Normal Phase Walk
Normal Phase Buff
Normal Phase Summon
Normal Phase Attack Combo 1
Normal Phase Attack Combo 2
Normal Phase Charge/Shield Bash Attack
Normal Phase Ranged Attack 1 (AoE)
Normal Phase Ranged Attack 2 (Projectile) [?]

Shield Phase Idle
Shield Phase Walk
Shield Phase Melee Attack
Shield Phase Ranged Attack (Projectile) [?]

Upper Body Attack 1 [?]
Upper Body Attack 2 [?]
