### ISSUE TITLE
Escape Menu Programming - Partial Completion

### ISSUE THREAD

**Issue by Khrune** [anuragpapineni/3DCapstoneGame#159]

**Comment by dhagandev** [comment]
-Lock camera
-Add D-pad control for selection

**Comment by dhagandev** [comment]
-Add Button to return to main game

**Comment by dhagandev** [comment]
Camera is locked.
D-pad control for selection should be working but controller does not seem to be playing nice with my computer, so testing isn't working.
Added the button to return to main game.

TODO:
Add functionality for options and main menu buttons

**Comment by dhagandev** [comment]
TODO: 
Add ability to press esc/p again to alter if menu shows/not.

**Comment by dhagandev** [comment]
Bug reported: Mouse still present when you resume. 

Bug should be fixed now. In addition, can alternate between in game menu and audio menu.

**Comment by dhagandev** [comment]
BLOCKED. Cannot proceed with esc reverting to game play again; UE does not have that type of functionality within UMG that I can tell, and the best work around would be to wrap all player input related functions except opening the menu in a bool that dictates whether or not it runs... Which sounds gawky to me.
