### ISSUE TITLE
Audio Control Menu

### ISSUE THREAD

**Issue by Khrune** [anuragpapineni/3DCapstoneGame#176]

**Comment by dhagandev** [comment]
Gamepad functionality

**Comment by dhagandev** [comment]
Invert controller controls - should this invert mouse too?

**Comment by wilchett** [comment]
Anything other than max is very quiet or silent, and you can not return to max after altering the bar.
Also, upon leaving the menu, sliders revert to max while the audio keeps changes made.

**Comment by dhagandev** [comment]
Values are being stored upon return, there is some gamepad control, but it is not clear as to how to use the controller with it. 
Must press "A" or "Enter" to select the slider, then left or right to adjust it. Must press enter again to move away from the slider. There should be a better way of doing this; will talk to @Khrune about this later.

**Comment by dhagandev** [comment]
Values are getting stored; need to design a better way to show players that a slider is highlighted
