### ISSUE TITLE
BT Enemy Aggro Framework

### ISSUE THREAD

**Issue by Khrune** [anuragpapineni/3DCapstoneGame#320]
**We can all (and maybe should?) talk about this before implementing it**

Enemies should change their target based on certain factors.

• Which player is closest. This is the basic, default starting behavior. This shouldn't carry as much weight as the other factors once a fight has been engaged.

• Which player has lower health. This is important for smarter enemies, especially those in the dark wing. Flankers/strikers should weight players with lower health with higher priority.

• Which player has recently damaged the enemy: This one may be a little awkward, given how we've designed the combat of our game. If one player has done at least 1.5x or 2x as much damage as the other player in the last 10 seconds, aggro should switch to that player.

**Comment by ZackMisso** [comment]
This will be a task for only the aggro framework. Each individual AI will be different in terms of what will take priority when choosing a target
