### ISSUE TITLE
Box that Kills you

### ISSUE THREAD

**Issue by Khrune** [anuragpapineni/3DCapstoneGame#95]
Collision volume that does damage over time
with a mesh inside it

**Comment by dhagandev** [comment]
Concerned about it not continuously applying damage, but I think it is working.

**Comment by Khrune** [comment]
@dhagandev Please expose the float that defines damage per tick, so I can change that for a single instance of the BP in a level

**Comment by dhagandev** [comment]
Done, can now create multiple boxes with different damage values
